### ISSUE TITLE
Compute energy ONLY last iteration of pmap_nanoDFT

### ISSUE THREAD

**Issue by akrzgc** [graphcore-research/pyscf-ipu#25]
https://github.com/graphcore-research/pyscf-ipu/blob/e42d60bd84931533a6cc04eb2aad57eb2b10342e/nanoDFT/experimental_pmap_nanoDFT.py#L128C52-L128C52

This version circumvents J and K by computing their difference directly. This is faster and simpler but means we cannot compute energy at each iteration. We don't need energy at each iteration, we just want it at the last iteration.
TODO: compute the energy at the last iteration.

**Comment by AlexanderMath** [comment]
During discussion we realized it is possible to compute energy using `dJK`. This means we can indeed compute energy every iteration while still reducing the number of einsums from 2 to 1.  

**Task:** On [line 35](https://github.com/graphcore-research/pyscf-ipu/blob/6ed968cc81aa68fbce10a10262516f2b76fba6a7/nanoDFT/experimental_pmap_nanoDFT.py#L33) change `E_J/2-E_K/4` to `np.sum(density_matrix * dJK)/2` and check energy agrees with PySCF. 

**Follow-up refactoring:** 
1. Create a variable `E_J_K = np.sum(density_matrix*dJK)` and use `E_J_K/2` in energy expression. 
2. Remove `J, K` everywhere. 
3. On line 73 log `dJK` and on line 263 use the `dJK` you just logged instead of `(J, K)`. 
4. Change the size of `log["matrices"]` from `(iterations, 4, N, N)` to `(iterations, 3, N, N)`; we removed `J, K` with `dJK`. 
5. Maybe rename `dJK` to `difference_J_K`?

**Why can we compute energy this way?** On [line 33](https://github.com/graphcore-research/pyscf-ipu/blob/6ed968cc81aa68fbce10a10262516f2b76fba6a7/nanoDFT/experimental_pmap_nanoDFT.py#L33) the term `E_J/2-E_K/4` appears, but we can rewrite this as follows:

`E_J/2-E_K/4=(E_J-E_K/2)/2=np.sum(density_matrix * (J-K/2) / 2`

Because `K` was previously multiplied with `HYB_B3LYP` on [line 82](https://github.com/graphcore-research/pyscf-ipu/blob/6ed968cc81aa68fbce10a10262516f2b76fba6a7/nanoDFT/nanoDFT.py#L82), we then get 

`E_J/2-E_K/4=...=np.sum(density_matrix * (J-K/2*HYB_B3LYP) / 2`

But `dJK` was designed to be exactly `dJK=J-K/2*HYB_B3LYP`. This is the reason we can exchange `E_J/2-E_K/4` on line 33 with `E_J/2-E_K/4 = np.sum( density_matrix * dJK) / 2`.

**Comment by akrzgc** [comment]
The PR solving the #25 issue and also solving the bug in `experimental_pmap_nanoDFT.py` was pushed:
https://github.com/graphcore-research/pyscf-ipu/pull/42

**Comment by AlexanderMath** [comment]
Fixed 🎉 🚀
